// <auto-generated />
namespace WebUI.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class DelTestClass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DelTestClass));
        
        string IMigrationMetadata.Id
        {
            get { return "201212201429359_DelTestClass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
